database:
  image: postgres
  environment:
    - POSTGRES_USER=care_adopt_backend
    - POSTGRES_PASSWORD=care_adopt_backend
  ports:
  - "5432:5432"
backend:
  build: .
  command: bash /care_adopt_backend/server/django_devserver.sh
  links:
  - database
  ports:
  - "8000:8000"
  environment:
    DB_HOST: services_database_1
    PYTHONUNBUFFERED: 1