database:
  image: postgres
  environment:
    - POSTGRES_USER=care_adopt_backend
    - POSTGRES_PASSWORD=care_adopt_backend
  ports:
  - "5432:5432"
backend:
  build: .
  command: bash /care_adopt_backend/server/django_devserver.sh
  volumes:
  - .:/care_adopt_backend
  links:
  - database
  ports:
  - "8900:8000"
  environment:
    DB_HOST: database
    PYTHONUNBUFFERED: 1
